config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'blogs#index'
  resources :blogs

  # 保留ページのルーティング
  get 'blogs/:id/task' => 'blogs#task', as:'task_blog'

  #ホームページのルーティング
  get 'home/home' => 'home#home'
  # トップページのルーティング
  get 'home/index' => 'home#index'
  # タスクマネージページのルーティング
  get 'home/manager' => 'home#manager'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/register_tag.rb
class RegisterTag < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user!

  def index
    @blogs = Blog.all
    @overlapping_blogs = overlapping_blogs(@blogs)
    @filtered_blogs = @blogs.select { |blog| blog.category == "task" || blog.deadline.present? }
    @upcoming_blogs = @filtered_blogs.select do |blog|
      (blog.start_time >= Date.today && blog.start_time <= 3.days.from_now) || 
      (blog.deadline.present? && blog.deadline >= Date.today && blog.deadline <= 3.days.from_now)
    end
    @next_week_blogs = @filtered_blogs.select do |blog|
      (blog.start_time >= Date.today && blog.start_time <= 1.week.from_now) || 
      (blog.deadline.present? && blog.deadline >= Date.today && blog.deadline <= 1.week.from_now)
    end

  end
  
  def overlapping_blogs(blogs)
    overlapping = []
  
    blogs.each do |blog1|
      next if blog1.start_time.nil? || blog1.finish_time.nil? # nilチェック
  
      blogs.each do |blog2|
        next if blog1 == blog2 # 同じブログを比較しない
        next if blog2.start_time.nil? || blog2.finish_time.nil? # nilチェック
  
        if blog1.start_time.to_date == blog2.start_time.to_date # 日付が同じ
          if (blog1.start_time < blog2.finish_time) && (blog2.start_time < blog1.finish_time) # 時間帯が重なる
            overlapping << blog1
            break # 重複が見つかったら次のブログへ
          end
        end
      end
    end
  
    overlapping
  end

  def new
    @blog = Blog.new
  end

  def show
    puts params.inspect
    @blog = Blog.find(params[:id])
  end

  def task
    puts params.inspect
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_parameter)
    if @blog.save
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time, :category, :deadline, :finish_time, :color)
  end

  def blogs_params
    params.require(:register).permit(:tag_ids)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index

    end

    def home

    end

    def manager
        @blog = Blog.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/edit.html.erb
<div class="edit-form-container" style="background-image: url('<%= asset_path('memo-background2.png') %>'); ">

<body >
<%= form_with(model: @blog, local: true) do |form| %>

    <h1 class='sub-header'>予定を編集</h1>

    <div class="title">
        <%= form.text_field :title, placeholder: "タイトル", class: 'custom-title' %>
    </div>
    <br>
    <div class="content">
        <%= form.text_area :content, placeholder: "メモ", class: 'custom-content' %>
    </div>
    <br>
    <div class="time">
        <%= form.label :開始時間 %>
        <%= form.datetime_select :start_time %>
    </div>
    <div class="ftime">
        <%= form.label :終了時間 %>
        <%= form.datetime_select :finish_time %>
    </div>
    <br>
    <div class="category">
        <%= form.select :category, [["予定","show"],["タスク","task"]], include_blank: "どの投稿？",  class: "category-select" %>
    </div>
    <br>
    <div class="deadline">
        <%= form.label :締め切り %>
        <%= form.datetime_select :deadline %>
    </div>
    <br>
    <div class="submit">
        <%= form.submit "変更" %>
    </div>

<% end %>
</body>

</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>


<head>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Noto Sans JP', sans-serif;
        }
        /* 他のスタイルもここに追加 */
    </style>
</head>


<h1 class='custom-header'>
<div style="display: flex; align-items: left; justify-content: space-between; margin-right: 20px;">
My Schedule
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
</div>
</h1>

<div class="flex-container">
    <% filtered_blogs = @blogs.select { |blog| blog.category == "task" || blog.deadline.present?} %>
        <% if filtered_blogs.any? { |blog| ( blog.start_time >= Date.today && blog.start_time <= 3.days.from_now ) || ( blog.deadline.present? && blog.deadline >= Date.today && blog.deadline <= 3.days.from_now ) } %>
            <div class="box3days">〆切間近</div>
        <% elsif filtered_blogs.any? { |blog| ( blog.start_time >= Date.today && blog.start_time <= 1.week.from_now ) || ( blog.deadline.present? && blog.deadline >= Date.today && blog.deadline <= 1.week.from_now ) } %>
            <div class="box1week">〆切近い</div>
        <% else %>
            <div class="boxnotask">タスクなし</div>
        <% end %>
    <button id="toggle-button" class="toggle-button"> ∧</button>
</div>

    <div id="blog-list">


<table >

    <tbody>
    <% filtered_blogs.each do |blog| %>
    <div class="blog-post <%= 'show-category' if blog.category == 'show' %>" style="background-image: url('<%= asset_path('post-background.png') %>');" >
        <div>
            <div class='blog-title'><%= blog.title %></div>
        </div>
    <div style="display: flex; align-items: left; justify-content: space-between;">
    <div>
        <div class='date-font'>
            <div class='date'><%= blog.start_time.strftime("%Y") + "年" + blog.start_time.strftime("%m") + "月" + blog.start_time.strftime("%d") + "日" %></div>
        </div>
        <div class='time-font'>
        <div class='time'><%= "　" + blog.start_time.strftime("%H:%M") + "　＞＞　" + blog.finish_time.strftime("%H:%M")%></div>
        </div>
        <div>
            <div class='date-time'>締め切り：　<%= blog.deadline.present? ? blog.deadline.strftime("%Y") + "年" + blog.deadline.strftime("%m") + "月" + blog.deadline.strftime("%d") + "日　" + blog.deadline.strftime("%H:%M") : "未設定" %></div>
        </div>
        <div>
            <div style="display: flex; align-items: center;">
            <% if blog.category == "show" %>
            <%= link_to 'あああ', blog_path(blog.id) %>
            <% else %>
            <%= button_to '管理する', edit_blog_path(blog.id), method: :get, class: "inline-button" %>
            <% end %>
            <%= button_to '削除',blog_path(blog.id), method: :delete, class: "inline-button" %>
            </div>
        </div>
    </div>

            <div>
            <label for="content_<%= blog.id %>"></label>
            <textarea class='memo-textarea' id="content_<%= blog.id %>" name="blog[content]" rows="4" cols="50">
            <%= blog.content %>
            </textarea>
            </div>

        </div>
        </div>
    </div>
    <% end %>
    </tbody>


</table>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
    // "show-category"クラスを持つすべての要素を取得
    const showPosts = document.querySelectorAll('.show-category');
    
    // 各要素を削除
    showPosts.forEach(function(post) {
        post.remove();
    });
});
</script>

<br>

<%= link_to '予定を追加', new_blog_path %>

<%= month_calendar events: @blogs do |date, blogs| %>
    <div class="date-box <%= 'today' if date == Date.today %> <%= 'single-digit' if date.day < 10 %> 
    <%= 'double-digit' if date.day >= 10 %> <%= 'red-sunday' if date.wday == 0 %> <%= 'blue-saturday' if date.wday == 6 %>">
    <span class="date-day"><%= date.day %></span>
    </div>
    <% blogs.each do |blog| %>
    <div class="box <%= 'overlapping' if @overlapping_blogs.include?(blog) %> <%= 'task-box' if blog.category == 'task' %> ">
    <span class="box-text">
        <% if blog.category == "show" %>
        <%= link_to blog.title, blog, class: "box-link" %>
        <% else %>
        <%= link_to blog.title, edit_blog_path(blog.id), class: "box-link" %>
        <% end %>
    </span>
    </div>
    <% end %>
<% end %>


<script>
    let isVisible = true; // 初期状態を設定

    document.addEventListener("DOMContentLoaded", function() {
        const button = document.getElementById("toggle-button");
        const blogList = document.getElementById("blog-list"); // div全体を取得

        button.addEventListener("click", function() {
            if (isVisible) {
                blogList.style.display = "none"; // tbodyを非表示
                button.textContent = " ∨ タスクを表示"; // ボタンのテキストを変更
            } else {
                blogList.style.display = ""; // tbodyを表示（デフォルトに戻す）
                button.textContent = " ∧"; // ボタンのテキストを変更
            }
            isVisible = !isVisible; // 状態を反転
        });
    });
</script>

app/views/blogs/new.html.erb
<div class="edit-form-container" style="background-image: url('<%= asset_path('memo-background2.png') %>'); ">

<%= form_with(model: @blog, local: true) do |form| %>

    <h1 class='sub-header'>新しい予定を作成</h1>
    
    <div class="title">
        <%= form.text_field :title, placeholder: "タイトル", class: 'custom-title' %>
    </div>
    <br>
    <div class="content">
        <%= form.text_area :content, placeholder: "メモ", class: 'custom-content' %>
    </div>
    <br>
    <div class="start_time">
        <%= form.label :開始時間 %>
        <%= form.datetime_select :start_time %>
    </div>
    <div class="finish_time">
        <%= form.label :終了時間 %>
        <%= form.datetime_select :finish_time %>
    </div>
    <br>
    <div class="category">
        <%= form.select :category, [["予定","show"],["タスク","task"]], include_blank: "どの投稿？", class: "category-select" %>
    </div>
    <br>
    <div class="deadline">
        <%= form.label :締め切り %>
        <%= form.datetime_select :deadline, include_blank: true%>
    </div>
    <br>

    <div class="submit">
        <%= form.submit "予定を作成" %>
    </div>


    <% end %>

</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>タイトル</strong>
    <% if @blog.category == "show" %>
    <%= @blog.title %>
    <% end %>
</p>

<p>
    <strong>時間</strong>
    <% if @blog.category == "show" %>
    <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
    <% end %>
</p>



<p>
    <strong>内容</strong>
    <% if @blog.category == "show" %>
    <%= @blog.content %>
    <% end %>
</p>

<p>
<%= button_to '削除',blog_path(@blog.id), method: :delete %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/task.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>タイトル</strong>
    <% if @blog.category == "task" %>
    <%= @blog.title %>
    <% end %>
</p>

<p>
    <strong>時間</strong>
    <% if @blog.category == "task" %>
    <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
    <% end %>
</p>

<p>
    <strong>内容</strong>
    <% if @blog.category == "task" %>
    <%= @blog.content %>
    <% end %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/home/home.html.erb
<head>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Noto Sans JP', sans-serif;
        }
        /* 他のスタイルもここに追加 */
    </style>
</head>


<body class="gray-background" >

<div class="l-container" id="image-container" ></div>

<div class="l-container-text" id="text-container" >通常の予定とは別に、未確定な予定を「タスク」として登録することができます。このとき、締め切りを設定することもできます。</div>

<%= link_to "ログイン", blogs_path , class: "login-link" %>
<%= link_to "新規登録", new_user_registration_path , class: "signup-link" %>

<div class='button-container' >
<button class='select-button selected'
data-text="通常の予定とは別に、未確定な予定を「タスク」として登録することができます。このとき、締め切りを設定することもできます。" 
onclick="changeBackgroundImage('setumeigazou-1.png', this)"></button>

<button class='select-button'
data-text="「タスク」として登録された予定はカレンダー上でオレンジ色で表示されます。また、予定にブッキングが生じた場合は赤色で表示されます。" 
onclick="changeBackgroundImage('setumeigazou-2.png', this)"></button>

<button class='select-button'
data-text="締め切りや予定の日が近づいてきたとき、ブッキングがあったときは、お知らせします。「∨ タスクを表示」を押して、タスクの確認、管理を行なってください。"
onclick="changeBackgroundImage('setumeigazou-3.png', this)"></button>
</div>

<script>

let lastSelectedButton = document.querySelector('.select-button.selected');  // 直前に選択されたボタンを保持

function changeBackgroundImage(imageUrl, button) {
    document.getElementById('image-container').style.backgroundImage = `url('/assets/${imageUrl}')`;

    // テキストの変更
    const newText = button.getAttribute('data-text');
    document.getElementById('text-container').textContent = newText;

    // 直前のボタンがあれば、色を元に戻す
    if (lastSelectedButton) {
        lastSelectedButton.classList.remove('selected');
    }

    // 現在のボタンを選択状態にする
    button.classList.add('selected');
    lastSelectedButton = button; // 現在のボタンを更新
}
</script>


</body>

app/views/home/index.html.erb
<body class="gray-background">
    <div class="p-fv">
        <%= link_to 'Start', home_home_path, class: 'start-link' %>
    </div>
</body>

app/views/home/manager.html.erb
ああああああああ！

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Originalapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <% day_classes = [] %>
            <% day_classes << 'weekend' if day.saturday? || day.sunday? %>

            <%= content_tag :td, class: "#{calendar.td_classes_for(day)} #{day_classes.join(' ')}".strip do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
      <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れましたか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>